# Generated by Django 2.1 on 2018-09-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookbookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookbook_type', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200, unique=True)),
                ('recipe_instructions', models.TextField(blank=True, null=True)),
                ('preparation_time_minutes', models.FloatField(blank=True, null=True)),
                ('cookbook_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mealplanner.CookbookType')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
                ('is_plural', models.BooleanField()),
                ('match_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='mealplanner.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='WeekOfDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_of_date', models.DateField(unique=True)),
                ('recipes', models.ManyToManyField(through='mealplanner.DayAssignment', to='mealplanner.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipeelement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Unit'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='mealplanner.RecipeElement', to='mealplanner.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mealplanner.RecipeType'),
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.WeekOfDate'),
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Day'),
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='meal_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='mealplanner.MealType'),
        ),
        migrations.AddField(
            model_name='dayassignment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mealplanner.Recipe'),
        ),
        migrations.AddField(
            model_name='day',
            name='recipes',
            field=models.ManyToManyField(through='mealplanner.DayAssignment', to='mealplanner.Recipe'),
        ),
    ]
