# Generated by Django 2.1 on 2018-09-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_auto_20180918_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseHistory',
            new_name='Purchase',
        ),
    ]
