# Generated by Django 2.1 on 2018-09-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0003_auto_20180918_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='was_sale',
            field=models.BooleanField(default=0),
        ),
    ]
