# Generated by Django 2.1 on 2018-09-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0004_purchase_was_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='was_sale',
            new_name='on_sale',
        ),
    ]
